services:
  elasticsearch:
    image: elasticsearch:7.10.1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.95"
          memory: 4G
    restart: always
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=true 
      - cluster.name=docker-cluster
      - ELASTIC_PASSWORD=${OPENSEARCH_PASSWD}
      - TZ=America/Sao_Paulo
    healthcheck:
      test: curl -u elastic:${OPENSEARCH_PASSWD} -f http://elasticsearch:9200/_cluster/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
        - rede
  kibana:
    depends_on:
       - elasticsearch
    image: kibana:7.10.1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.95"
          memory: 2G
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${OPENSEARCH_USER}
      - ELASTICSEARCH_PASSWORD=${OPENSEARCH_PASSWD}
      - TZ=America/Sao_Paulo
    healthcheck:
      test: curl -f http://kibana:5601/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    ports:
      - "5601:5601"
    networks:
        - rede
  minio-s3:
    hostname: minio-s3
    container_name: minio-s3
    image: bitnami/minio:2023
    ports: 
      - "9000:9000"
      - "9001:9001"
    environment: 
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - TZ=America/Sao_Paulo
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
    volumes: 
      - minio_data:/data
      - minio_certs:/certs
    networks:
      - rede

volumes:
  elastic_data:
  minio_data:
  minio_certs:

networks:
  rede:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.4.0.0/16